name: Build and test
on: push

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.10.7]
        poetry-version: [1.2.0]
        os: [ubuntu-18.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'
      - uses: actions/cache@v3
        with:
          path: ./.venv/  # what we cache: the virtualenv
          key: ${{ runner.os }}-venv-${{ env.PYTHON_VERSION }}-${{ hashFiles('**/poetry.lock') }}
      - uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - run: poetry install
      - run: poetry run pytest .